---
title: "Theory of Infectious Disease"
subtitle: Homework 4
author: "Aaron A. King"
output:
  pdf_document: default
params:
  prefix: "hw4"
---

\newcommand\prob[1]{\mathbb{P}\left[{#1}\right]}
\newcommand\expect[1]{\mathbb{E}\left[{#1}\right]}
\newcommand{\dd}[1]{\mathrm{d}{#1}}
\newcommand{\pd}[2]{\frac{\partial{#1}}{\partial{#2}}}
\newcommand{\deriv}[2]{\frac{\dd{#1}}{\dd{#2}}}
\newcommand\E[1]{\expect{#1}}
\newcommand\var[1]{\mathrm{Var}\left[{#1}\right]}
\newcommand\dist[2]{\mathrm{#1}\left(#2\right)}
\newcommand\dlta[1]{{\Delta}{#1}}
\newcommand\lik{\mathcal{L}}
\newcommand\loglik{\ell}
\newcommand\equals{{=\,}}
\newcommand\R{\mathbb{R}}
\newcommand\data[1]{#1^*}
\newcommand\params{\, ; \,}


```{r setup, include=FALSE}
knitr::opts_chunk$set(
    echo = FALSE, cache=TRUE,
    fig.align="center",
    cache.path=paste0("cache/",params$prefix),
    fig.path=paste0("figure/",params$prefix))
library(ggplot2)
library(reshape2)
library(plyr)
library(grid)
```

### Dynamics of vector-borne disease

Using **R** and **deSolve**, implement a numerical solver of the vector-borne disease model described in Keeling \& Rohani Eqs. 4.16.
Using the top two panels of Fig. 4.13 as a guide, come up with reasonable values for the model parameters and explore the model's dynamics.

### Fast-slow reduction

Next, implement the fast-slow reduction of the model.
This is captured in the second pair of displayed differential equations in Box 4.2.
Use **R** and **deSolve** to solve these equations, using the same parameters as before.
How are the dynamics of the two models related?

### Seasonal forcing in SIR dynamics

Use numerical solutions to explore the dynamics of the seasonally-forced SIR model expressed in Eqs. 5.2--5.4.
Use Fig. 5.6 as a guide.
